TFile * output_root = new TFile("./roots/IT_CLS_DPHI_CSC.root", "RECREATE");
void IT_CLS_DPHI_CSC()
{
//=========Macro generated from canvas: IT_CLS_DPHI_CSC/IT_CLS_DPHI_CSC
//=========  (Thu May  1 02:46:38 2025) by ROOT version 6.22/09
   TCanvas *IT_CLS_DPHI_CSC = new TCanvas("IT_CLS_DPHI_CSC", "IT_CLS_DPHI_CSC",0,0,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   IT_CLS_DPHI_CSC->SetHighLightColor(2);
   IT_CLS_DPHI_CSC->Range(-44.48398,0.6425,596.0854,3.3925);
   IT_CLS_DPHI_CSC->SetFillColor(0);
   IT_CLS_DPHI_CSC->SetBorderMode(0);
   IT_CLS_DPHI_CSC->SetBorderSize(2);
   IT_CLS_DPHI_CSC->SetTickx(1);
   IT_CLS_DPHI_CSC->SetTicky(1);
   IT_CLS_DPHI_CSC->SetLeftMargin(0.1475);
   IT_CLS_DPHI_CSC->SetRightMargin(0.15);
   IT_CLS_DPHI_CSC->SetTopMargin(0.07);
   IT_CLS_DPHI_CSC->SetBottomMargin(0.13);
   IT_CLS_DPHI_CSC->SetFrameFillStyle(0);
   IT_CLS_DPHI_CSC->SetFrameBorderMode(0);
   IT_CLS_DPHI_CSC->SetFrameFillStyle(0);
   IT_CLS_DPHI_CSC->SetFrameBorderMode(0);
   
   TH1F *hframe__13 = new TH1F("hframe__13","",1000,50,500);
   hframe__13->SetMinimum(1);
   hframe__13->SetMaximum(3.2);
   hframe__13->SetDirectory(0);
   hframe__13->SetStats(0);
   hframe__13->SetLineStyle(0);
   hframe__13->SetMarkerStyle(20);
   hframe__13->GetXaxis()->SetTitle("N_{hits}");
   hframe__13->GetXaxis()->SetLabelFont(42);
   hframe__13->GetXaxis()->SetLabelOffset(0.012);
   hframe__13->GetXaxis()->SetLabelSize(0.05);
   hframe__13->GetXaxis()->SetTitleSize(0.06);
   hframe__13->GetXaxis()->SetTitleOffset(0.9);
   hframe__13->GetXaxis()->SetTitleFont(42);
   hframe__13->GetYaxis()->SetTitle("#Delta#phi(cluster,    #mu_{ trigger } )");
   hframe__13->GetYaxis()->SetLabelFont(42);
   hframe__13->GetYaxis()->SetLabelOffset(0.012);
   hframe__13->GetYaxis()->SetLabelSize(0.05);
   hframe__13->GetYaxis()->SetTitleSize(0.06);
   hframe__13->GetYaxis()->SetTitleFont(42);
   hframe__13->GetZaxis()->SetLabelFont(42);
   hframe__13->GetZaxis()->SetLabelOffset(0.012);
   hframe__13->GetZaxis()->SetLabelSize(0.05);
   hframe__13->GetZaxis()->SetTitleSize(0.06);
   hframe__13->GetZaxis()->SetTitleOffset(1);
   hframe__13->GetZaxis()->SetTitleFont(42);
   hframe__13->Draw("AXIS");
   TLatex *   tex = new TLatex(0.8875,0.944,"#scale[1.0]{}");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.042);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1475,0.944,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0525);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2318556,0.944,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0399);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe_copy__14 = new TH1F("hframe_copy__14","",1000,50,500);
   hframe_copy__14->SetMinimum(1);
   hframe_copy__14->SetMaximum(3.2);
   hframe_copy__14->SetDirectory(0);
   hframe_copy__14->SetStats(0);
   hframe_copy__14->SetLineStyle(0);
   hframe_copy__14->SetMarkerStyle(20);
   hframe_copy__14->GetXaxis()->SetTitle("N_{hits}");
   hframe_copy__14->GetXaxis()->SetLabelFont(42);
   hframe_copy__14->GetXaxis()->SetLabelOffset(0.012);
   hframe_copy__14->GetXaxis()->SetLabelSize(0.05);
   hframe_copy__14->GetXaxis()->SetTitleSize(0.06);
   hframe_copy__14->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__14->GetXaxis()->SetTitleFont(42);
   hframe_copy__14->GetYaxis()->SetTitle("#Delta#phi(cluster,    #mu_{ trigger } )");
   hframe_copy__14->GetYaxis()->SetLabelFont(42);
   hframe_copy__14->GetYaxis()->SetLabelOffset(0.012);
   hframe_copy__14->GetYaxis()->SetLabelSize(0.05);
   hframe_copy__14->GetYaxis()->SetTitleSize(0.06);
   hframe_copy__14->GetYaxis()->SetTitleFont(42);
   hframe_copy__14->GetZaxis()->SetLabelFont(42);
   hframe_copy__14->GetZaxis()->SetLabelOffset(0.012);
   hframe_copy__14->GetZaxis()->SetLabelSize(0.05);
   hframe_copy__14->GetZaxis()->SetTitleSize(0.06);
   hframe_copy__14->GetZaxis()->SetTitleOffset(1);
   hframe_copy__14->GetZaxis()->SetTitleFont(42);
   hframe_copy__14->Draw("sameaxis");
   
   TH1F *hframe_copy__15 = new TH1F("hframe_copy__15","",1000,50,500);
   hframe_copy__15->SetMinimum(1);
   hframe_copy__15->SetMaximum(3.2);
   hframe_copy__15->SetDirectory(0);
   hframe_copy__15->SetStats(0);
   hframe_copy__15->SetLineStyle(0);
   hframe_copy__15->SetMarkerStyle(20);
   hframe_copy__15->GetXaxis()->SetTitle("N_{hits}");
   hframe_copy__15->GetXaxis()->SetLabelFont(42);
   hframe_copy__15->GetXaxis()->SetLabelOffset(0.012);
   hframe_copy__15->GetXaxis()->SetLabelSize(0.05);
   hframe_copy__15->GetXaxis()->SetTitleSize(0.06);
   hframe_copy__15->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__15->GetXaxis()->SetTitleFont(42);
   hframe_copy__15->GetYaxis()->SetTitle("#Delta#phi(cluster,    #mu_{ trigger } )");
   hframe_copy__15->GetYaxis()->SetLabelFont(42);
   hframe_copy__15->GetYaxis()->SetLabelOffset(0.012);
   hframe_copy__15->GetYaxis()->SetLabelSize(0.05);
   hframe_copy__15->GetYaxis()->SetTitleSize(0.06);
   hframe_copy__15->GetYaxis()->SetTitleFont(42);
   hframe_copy__15->GetZaxis()->SetLabelFont(42);
   hframe_copy__15->GetZaxis()->SetLabelOffset(0.012);
   hframe_copy__15->GetZaxis()->SetLabelSize(0.05);
   hframe_copy__15->GetZaxis()->SetTitleSize(0.06);
   hframe_copy__15->GetZaxis()->SetTitleOffset(1);
   hframe_copy__15->GetZaxis()->SetTitleFont(42);
   hframe_copy__15->Draw("sameaxis");
   
   TH1F *hframe_copy__16 = new TH1F("hframe_copy__16","",1000,50,500);
   hframe_copy__16->SetMinimum(1);
   hframe_copy__16->SetMaximum(3.2);
   hframe_copy__16->SetDirectory(0);
   hframe_copy__16->SetStats(0);
   hframe_copy__16->SetLineStyle(0);
   hframe_copy__16->SetMarkerStyle(20);
   hframe_copy__16->GetXaxis()->SetTitle("N_{hits}");
   hframe_copy__16->GetXaxis()->SetLabelFont(42);
   hframe_copy__16->GetXaxis()->SetLabelOffset(0.012);
   hframe_copy__16->GetXaxis()->SetLabelSize(0.05);
   hframe_copy__16->GetXaxis()->SetTitleSize(0.06);
   hframe_copy__16->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__16->GetXaxis()->SetTitleFont(42);
   hframe_copy__16->GetYaxis()->SetTitle("#Delta#phi(cluster,    #mu_{ trigger } )");
   hframe_copy__16->GetYaxis()->SetLabelFont(42);
   hframe_copy__16->GetYaxis()->SetLabelOffset(0.012);
   hframe_copy__16->GetYaxis()->SetLabelSize(0.05);
   hframe_copy__16->GetYaxis()->SetTitleSize(0.06);
   hframe_copy__16->GetYaxis()->SetTitleFont(42);
   hframe_copy__16->GetZaxis()->SetLabelFont(42);
   hframe_copy__16->GetZaxis()->SetLabelOffset(0.012);
   hframe_copy__16->GetZaxis()->SetLabelSize(0.05);
   hframe_copy__16->GetZaxis()->SetTitleSize(0.06);
   hframe_copy__16->GetZaxis()->SetTitleOffset(1);
   hframe_copy__16->GetZaxis()->SetTitleFont(42);
   hframe_copy__16->Draw("sameaxis");
      tex = new TLatex(0.15,0.94,"CMS");
tex->SetNDC();
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.58,0.94,"41.6 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH2F *h1_swap = new TH2F("h1_swap","h1_swap",45,50,500,40,0,4);
   h1_swap->SetMaximum(0);
   h1_swap->SetEntries(1800);
   h1_swap->SetDirectory(0);
   h1_swap->SetContour(20);
   h1_swap->SetContourLevel(0,0);
   h1_swap->SetContourLevel(1,0);
   h1_swap->SetContourLevel(2,0);
   h1_swap->SetContourLevel(3,0);
   h1_swap->SetContourLevel(4,0);
   h1_swap->SetContourLevel(5,0);
   h1_swap->SetContourLevel(6,0);
   h1_swap->SetContourLevel(7,0);
   h1_swap->SetContourLevel(8,0);
   h1_swap->SetContourLevel(9,0);
   h1_swap->SetContourLevel(10,0);
   h1_swap->SetContourLevel(11,0);
   h1_swap->SetContourLevel(12,0);
   h1_swap->SetContourLevel(13,0);
   h1_swap->SetContourLevel(14,0);
   h1_swap->SetContourLevel(15,0);
   h1_swap->SetContourLevel(16,0);
   h1_swap->SetContourLevel(17,0);
   h1_swap->SetContourLevel(18,0);
   h1_swap->SetContourLevel(19,0);
   
   TPaletteAxis *palette = new TPaletteAxis(503.2028,1,532.0285,3.2,h1_swap);
   palette->SetLabelColor(1);
   palette->SetLabelFont(42);
   palette->SetLabelOffset(0.012);
   palette->SetLabelSize(0.05);
   palette->SetTitleOffset(1);
   palette->SetTitleSize(0.04);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#1e836b");
   palette->SetFillColor(ci);
   palette->SetFillStyle(1001);
   h1_swap->GetListOfFunctions()->Add(palette,"br");
   h1_swap->SetLineStyle(0);
   h1_swap->SetMarkerStyle(20);
   h1_swap->GetXaxis()->SetLabelFont(42);
   h1_swap->GetXaxis()->SetLabelOffset(0.012);
   h1_swap->GetXaxis()->SetLabelSize(0.05);
   h1_swap->GetXaxis()->SetTitleSize(0.06);
   h1_swap->GetXaxis()->SetTitleOffset(0.9);
   h1_swap->GetXaxis()->SetTitleFont(42);
   h1_swap->GetYaxis()->SetRange(11,32);
   h1_swap->GetYaxis()->SetLabelFont(42);
   h1_swap->GetYaxis()->SetLabelOffset(0.012);
   h1_swap->GetYaxis()->SetLabelSize(0.05);
   h1_swap->GetYaxis()->SetTitleSize(0.06);
   h1_swap->GetYaxis()->SetTitleOffset(1.25);
   h1_swap->GetYaxis()->SetTitleFont(42);
   h1_swap->GetZaxis()->SetTitle("Events");
   h1_swap->GetZaxis()->SetNdivisions(5);
   h1_swap->GetZaxis()->SetLabelFont(42);
   h1_swap->GetZaxis()->SetLabelOffset(0.012);
   h1_swap->GetZaxis()->SetLabelSize(0.05);
   h1_swap->GetZaxis()->SetTitleSize(0.04);
   h1_swap->GetZaxis()->SetTitleOffset(1);
   h1_swap->GetZaxis()->SetTitleFont(42);
   h1_swap->Draw("same colz");
   
   TPaveText *pt = new TPaveText(380,2.5,410,3,"br");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextSize(0.15);
   TText *pt_LaTex = pt->AddText("A");
   pt_LaTex->SetTextColor(98);
   pt->Draw();
   
   pt = new TPaveText(380,1.5,410,2,"br");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextSize(0.15);
   pt_LaTex = pt->AddText("B");
   pt_LaTex->SetTextColor(98);
   pt->Draw();
   
   pt = new TPaveText(165,2.5,195,3,"br");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextSize(0.15);
   pt_LaTex = pt->AddText("C");
   pt_LaTex->SetTextColor(98);
   pt->Draw();
   
   pt = new TPaveText(165,1.5,195,2,"br");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextSize(0.15);
   pt_LaTex = pt->AddText("D");
   pt_LaTex->SetTextColor(98);
   pt->Draw();
   TLine *line = new TLine(310,1,310,3.2);
   line->SetLineColor(98);
   line->SetLineWidth(4);
   line->Draw();
   line = new TLine(50,2.2,500,2.2);
   line->SetLineColor(98);
   line->SetLineWidth(4);
   line->Draw();
   IT_CLS_DPHI_CSC->Modified();
   IT_CLS_DPHI_CSC->cd();
   IT_CLS_DPHI_CSC->SetSelected(IT_CLS_DPHI_CSC);

hframe__13->Write();
hframe_copy__14->Write();
hframe_copy__15->Write();
hframe_copy__16->Write();
h1_swap->Write();

}