void IT_CLS_DPHI_DT()
{
//=========Macro generated from canvas: IT_CLS_DPHI_DT/IT_CLS_DPHI_DT
//=========  (Thu May  1 02:46:38 2025) by ROOT version 6.22/09
   TCanvas *IT_CLS_DPHI_DT = new TCanvas("IT_CLS_DPHI_DT", "IT_CLS_DPHI_DT",0,0,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   IT_CLS_DPHI_DT->SetHighLightColor(2);
   IT_CLS_DPHI_DT->Range(-44.48398,0.6425,596.0854,3.3925);
   IT_CLS_DPHI_DT->SetFillColor(0);
   IT_CLS_DPHI_DT->SetBorderMode(0);
   IT_CLS_DPHI_DT->SetBorderSize(2);
   IT_CLS_DPHI_DT->SetTickx(1);
   IT_CLS_DPHI_DT->SetTicky(1);
   IT_CLS_DPHI_DT->SetLeftMargin(0.1475);
   IT_CLS_DPHI_DT->SetRightMargin(0.15);
   IT_CLS_DPHI_DT->SetTopMargin(0.07);
   IT_CLS_DPHI_DT->SetBottomMargin(0.13);
   IT_CLS_DPHI_DT->SetFrameFillStyle(0);
   IT_CLS_DPHI_DT->SetFrameBorderMode(0);
   IT_CLS_DPHI_DT->SetFrameFillStyle(0);
   IT_CLS_DPHI_DT->SetFrameBorderMode(0);
   
   TH1F *hframe__9 = new TH1F("hframe__9","",1000,50,500);
   hframe__9->SetMinimum(1);
   hframe__9->SetMaximum(3.2);
   hframe__9->SetDirectory(0);
   hframe__9->SetStats(0);
   hframe__9->SetLineStyle(0);
   hframe__9->SetMarkerStyle(20);
   hframe__9->GetXaxis()->SetTitle("N_{hits}");
   hframe__9->GetXaxis()->SetLabelFont(42);
   hframe__9->GetXaxis()->SetLabelOffset(0.012);
   hframe__9->GetXaxis()->SetLabelSize(0.05);
   hframe__9->GetXaxis()->SetTitleSize(0.06);
   hframe__9->GetXaxis()->SetTitleOffset(0.9);
   hframe__9->GetXaxis()->SetTitleFont(42);
   hframe__9->GetYaxis()->SetTitle("#Delta#phi(cluster,    #mu_{ trigger } )");
   hframe__9->GetYaxis()->SetLabelFont(42);
   hframe__9->GetYaxis()->SetLabelOffset(0.012);
   hframe__9->GetYaxis()->SetLabelSize(0.05);
   hframe__9->GetYaxis()->SetTitleSize(0.06);
   hframe__9->GetYaxis()->SetTitleFont(42);
   hframe__9->GetZaxis()->SetLabelFont(42);
   hframe__9->GetZaxis()->SetLabelOffset(0.012);
   hframe__9->GetZaxis()->SetLabelSize(0.05);
   hframe__9->GetZaxis()->SetTitleSize(0.06);
   hframe__9->GetZaxis()->SetTitleOffset(1);
   hframe__9->GetZaxis()->SetTitleFont(42);
   hframe__9->Draw("AXIS");
   TLatex *   tex = new TLatex(0.8875,0.944,"#scale[1.0]{}");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.042);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1475,0.944,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0525);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2318556,0.944,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0399);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe_copy__10 = new TH1F("hframe_copy__10","",1000,50,500);
   hframe_copy__10->SetMinimum(1);
   hframe_copy__10->SetMaximum(3.2);
   hframe_copy__10->SetDirectory(0);
   hframe_copy__10->SetStats(0);
   hframe_copy__10->SetLineStyle(0);
   hframe_copy__10->SetMarkerStyle(20);
   hframe_copy__10->GetXaxis()->SetTitle("N_{hits}");
   hframe_copy__10->GetXaxis()->SetLabelFont(42);
   hframe_copy__10->GetXaxis()->SetLabelOffset(0.012);
   hframe_copy__10->GetXaxis()->SetLabelSize(0.05);
   hframe_copy__10->GetXaxis()->SetTitleSize(0.06);
   hframe_copy__10->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__10->GetXaxis()->SetTitleFont(42);
   hframe_copy__10->GetYaxis()->SetTitle("#Delta#phi(cluster,    #mu_{ trigger } )");
   hframe_copy__10->GetYaxis()->SetLabelFont(42);
   hframe_copy__10->GetYaxis()->SetLabelOffset(0.012);
   hframe_copy__10->GetYaxis()->SetLabelSize(0.05);
   hframe_copy__10->GetYaxis()->SetTitleSize(0.06);
   hframe_copy__10->GetYaxis()->SetTitleFont(42);
   hframe_copy__10->GetZaxis()->SetLabelFont(42);
   hframe_copy__10->GetZaxis()->SetLabelOffset(0.012);
   hframe_copy__10->GetZaxis()->SetLabelSize(0.05);
   hframe_copy__10->GetZaxis()->SetTitleSize(0.06);
   hframe_copy__10->GetZaxis()->SetTitleOffset(1);
   hframe_copy__10->GetZaxis()->SetTitleFont(42);
   hframe_copy__10->Draw("sameaxis");
   
   TH1F *hframe_copy__11 = new TH1F("hframe_copy__11","",1000,50,500);
   hframe_copy__11->SetMinimum(1);
   hframe_copy__11->SetMaximum(3.2);
   hframe_copy__11->SetDirectory(0);
   hframe_copy__11->SetStats(0);
   hframe_copy__11->SetLineStyle(0);
   hframe_copy__11->SetMarkerStyle(20);
   hframe_copy__11->GetXaxis()->SetTitle("N_{hits}");
   hframe_copy__11->GetXaxis()->SetLabelFont(42);
   hframe_copy__11->GetXaxis()->SetLabelOffset(0.012);
   hframe_copy__11->GetXaxis()->SetLabelSize(0.05);
   hframe_copy__11->GetXaxis()->SetTitleSize(0.06);
   hframe_copy__11->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__11->GetXaxis()->SetTitleFont(42);
   hframe_copy__11->GetYaxis()->SetTitle("#Delta#phi(cluster,    #mu_{ trigger } )");
   hframe_copy__11->GetYaxis()->SetLabelFont(42);
   hframe_copy__11->GetYaxis()->SetLabelOffset(0.012);
   hframe_copy__11->GetYaxis()->SetLabelSize(0.05);
   hframe_copy__11->GetYaxis()->SetTitleSize(0.06);
   hframe_copy__11->GetYaxis()->SetTitleFont(42);
   hframe_copy__11->GetZaxis()->SetLabelFont(42);
   hframe_copy__11->GetZaxis()->SetLabelOffset(0.012);
   hframe_copy__11->GetZaxis()->SetLabelSize(0.05);
   hframe_copy__11->GetZaxis()->SetTitleSize(0.06);
   hframe_copy__11->GetZaxis()->SetTitleOffset(1);
   hframe_copy__11->GetZaxis()->SetTitleFont(42);
   hframe_copy__11->Draw("sameaxis");
   
   TH1F *hframe_copy__12 = new TH1F("hframe_copy__12","",1000,50,500);
   hframe_copy__12->SetMinimum(1);
   hframe_copy__12->SetMaximum(3.2);
   hframe_copy__12->SetDirectory(0);
   hframe_copy__12->SetStats(0);
   hframe_copy__12->SetLineStyle(0);
   hframe_copy__12->SetMarkerStyle(20);
   hframe_copy__12->GetXaxis()->SetTitle("N_{hits}");
   hframe_copy__12->GetXaxis()->SetLabelFont(42);
   hframe_copy__12->GetXaxis()->SetLabelOffset(0.012);
   hframe_copy__12->GetXaxis()->SetLabelSize(0.05);
   hframe_copy__12->GetXaxis()->SetTitleSize(0.06);
   hframe_copy__12->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__12->GetXaxis()->SetTitleFont(42);
   hframe_copy__12->GetYaxis()->SetTitle("#Delta#phi(cluster,    #mu_{ trigger } )");
   hframe_copy__12->GetYaxis()->SetLabelFont(42);
   hframe_copy__12->GetYaxis()->SetLabelOffset(0.012);
   hframe_copy__12->GetYaxis()->SetLabelSize(0.05);
   hframe_copy__12->GetYaxis()->SetTitleSize(0.06);
   hframe_copy__12->GetYaxis()->SetTitleFont(42);
   hframe_copy__12->GetZaxis()->SetLabelFont(42);
   hframe_copy__12->GetZaxis()->SetLabelOffset(0.012);
   hframe_copy__12->GetZaxis()->SetLabelSize(0.05);
   hframe_copy__12->GetZaxis()->SetTitleSize(0.06);
   hframe_copy__12->GetZaxis()->SetTitleOffset(1);
   hframe_copy__12->GetZaxis()->SetTitleFont(42);
   hframe_copy__12->Draw("sameaxis");
      tex = new TLatex(0.15,0.94,"CMS");
tex->SetNDC();
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.58,0.94,"41.6 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH2F *h1_swap = new TH2F("h1_swap","h1_swap",45,50,500,40,0,4);
   h1_swap->SetMaximum(0);
   h1_swap->SetEntries(1800);
   h1_swap->SetContour(20);
   h1_swap->SetContourLevel(0,0);
   h1_swap->SetContourLevel(1,0);
   h1_swap->SetContourLevel(2,0);
   h1_swap->SetContourLevel(3,0);
   h1_swap->SetContourLevel(4,0);
   h1_swap->SetContourLevel(5,0);
   h1_swap->SetContourLevel(6,0);
   h1_swap->SetContourLevel(7,0);
   h1_swap->SetContourLevel(8,0);
   h1_swap->SetContourLevel(9,0);
   h1_swap->SetContourLevel(10,0);
   h1_swap->SetContourLevel(11,0);
   h1_swap->SetContourLevel(12,0);
   h1_swap->SetContourLevel(13,0);
   h1_swap->SetContourLevel(14,0);
   h1_swap->SetContourLevel(15,0);
   h1_swap->SetContourLevel(16,0);
   h1_swap->SetContourLevel(17,0);
   h1_swap->SetContourLevel(18,0);
   h1_swap->SetContourLevel(19,0);
   
   TPaletteAxis *palette = new TPaletteAxis(503.2028,1,532.0285,3.2,h1_swap);
   palette->SetLabelColor(1);
   palette->SetLabelFont(42);
   palette->SetLabelOffset(0.012);
   palette->SetLabelSize(0.05);
   palette->SetTitleOffset(1);
   palette->SetTitleSize(0.04);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#1e836b");
   palette->SetFillColor(ci);
   palette->SetFillStyle(1001);
   h1_swap->GetListOfFunctions()->Add(palette,"br");
   h1_swap->SetLineStyle(0);
   h1_swap->SetMarkerStyle(20);
   h1_swap->GetXaxis()->SetLabelFont(42);
   h1_swap->GetXaxis()->SetLabelOffset(0.012);
   h1_swap->GetXaxis()->SetLabelSize(0.05);
   h1_swap->GetXaxis()->SetTitleSize(0.06);
   h1_swap->GetXaxis()->SetTitleOffset(0.9);
   h1_swap->GetXaxis()->SetTitleFont(42);
   h1_swap->GetYaxis()->SetRange(11,32);
   h1_swap->GetYaxis()->SetLabelFont(42);
   h1_swap->GetYaxis()->SetLabelOffset(0.012);
   h1_swap->GetYaxis()->SetLabelSize(0.05);
   h1_swap->GetYaxis()->SetTitleSize(0.06);
   h1_swap->GetYaxis()->SetTitleOffset(1.25);
   h1_swap->GetYaxis()->SetTitleFont(42);
   h1_swap->GetZaxis()->SetTitle("Events");
   h1_swap->GetZaxis()->SetNdivisions(5);
   h1_swap->GetZaxis()->SetLabelFont(42);
   h1_swap->GetZaxis()->SetLabelOffset(0.012);
   h1_swap->GetZaxis()->SetLabelSize(0.05);
   h1_swap->GetZaxis()->SetTitleSize(0.04);
   h1_swap->GetZaxis()->SetTitleOffset(1);
   h1_swap->GetZaxis()->SetTitleFont(42);
   h1_swap->Draw("same colz");
   
   TPaveText *pt = new TPaveText(380,2.5,410,3,"br");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextSize(0.15);
   TText *pt_LaTex = pt->AddText("A");
   pt_LaTex->SetTextColor(98);
   pt->Draw();
   
   pt = new TPaveText(380,1.5,410,2,"br");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextSize(0.15);
   pt_LaTex = pt->AddText("B");
   pt_LaTex->SetTextColor(98);
   pt->Draw();
   
   pt = new TPaveText(165,2.5,195,3,"br");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextSize(0.15);
   pt_LaTex = pt->AddText("C");
   pt_LaTex->SetTextColor(98);
   pt->Draw();
   
   pt = new TPaveText(165,1.5,195,2,"br");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextSize(0.15);
   pt_LaTex = pt->AddText("D");
   pt_LaTex->SetTextColor(98);
   pt->Draw();
   TLine *line = new TLine(310,1,310,3.2);
   line->SetLineColor(98);
   line->SetLineWidth(4);
   line->Draw();
   line = new TLine(50,2.2,500,2.2);
   line->SetLineColor(98);
   line->SetLineWidth(4);
   line->Draw();
   IT_CLS_DPHI_DT->Modified();
   IT_CLS_DPHI_DT->cd();
   IT_CLS_DPHI_DT->SetSelected(IT_CLS_DPHI_DT);
}
